runners:
  - name: oracle-runner
    cloud: oracle
    instance_type: VM.Standard2.4
    machine_image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa6m57xzoztlide4653fjavkm6dpksmz3kaa4gig4h34jod76aapva
    region: eu-frankfurt-1
    labels:
      - cirun-oracle
  - name: "nectar-runner-medium"
    cloud: "openstack"
    instance_type: "m3.medium"
    machine_image: "3fdc6cfa-f197-4dfd-a6b4-b0b9f7795b41"
    region: Melbourne
    labels:
      - "cirun-nectar-medium"
  - name: "nectar-runner-small"
    cloud: "openstack"
    instance_type: "m3.small"
    machine_image: "3fdc6cfa-f197-4dfd-a6b4-b0b9f7795b41"
    region: Melbourne
    labels:
      - "cirun-nectar-small"
