runners:
  - name: oracle-runner
    cloud: oracle
    instance_type: VM.Standard2.4
    machine_image: ocid1.image.oc1.eu-frankfurt-1.aaaaaaaakafaxdrc47g2kkhykusxzoomckdpshwenpbn44sgbbwpzfu33lwq
    region: eu-frankfurt-1
    labels:
      - cirun-oracle
  - name: "nectar-runner-medium"
    cloud: "openstack"
    instance_type: "r3.medium"
    machine_image: "4adcec13-2291-4bff-987f-d87f98d24379"
    region: Melbourne
    labels:
      - "cirun-nectar-medium"
  - name: "nectar-runner-small"
    cloud: "openstack"
    instance_type: "r3.small"
    machine_image: "4adcec13-2291-4bff-987f-d87f98d24379"
    region: Melbourne
    labels:
      - "cirun-nectar-small"  
  - name: "nectar-runner-large"
    cloud: "openstack"
    instance_type: "r3.large"
    machine_image: "4adcec13-2291-4bff-987f-d87f98d24379"
    region: Melbourne
    labels:
      - "cirun-nectar-large"
