name: segmentation pipeline test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ master ]
    paths:
      - README.md
      - run_0_dicomSort.py
      - run_1_dicomConvert.py
      - run_3_segment.py
      - run_5_analysis.py
      - interfaces/nipype_interface_fastsurfer.py
      - .github/workflows/test_segmentation_pipeline.yml
      - tests/run_test_segment.sh
      - aseg_labels.csv
  pull_request:
    branches: [ master ]
    paths:
      - README.md
      - run_0_dicomSort.py
      - run_1_dicomConvert.py
      - run_3_segment.py
      - run_5_analysis.py
      - interfaces/nipype_interface_fastsurfer.py
      - .github/workflows/test_segmentation_pipeline.yml
      - tests/run_test_segment.sh
      - aseg_labels.csv
    
jobs:
  test_segmentation_pipeline:
    runs-on: [self-hosted, oracle]
    steps:
    - name: segmentation pipeline
      run: |
        export timeStamp=`date +"%Y-%m-%d-%T"`
        git clone https://github.com/QSMxT/QSMxT.git /tmp/${timeStamp}/QSMxT
        /bin/bash /tmp/${timeStamp}/QSMxT/tests/run_test_segment.sh
