name: transparent singularity test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - setup.py
      - .github/workflows/test_transparent_singularity.yml
      - docs/_includes/miniconda_install.sh
      - docs/_includes/transparent_singularity_install.sh
      - docs/_config.yml
      - aseg_labels.csv
      - qsmxt/qsm_pipelines.json
      - qsmxt/cli/*.py
      - qsmxt/tests/test_transparent_singularity.sh
      - qsmxt/tests/utils.py
      - qsmxt/tests/setup_qsmxt.sh
      - qsmxt/interfaces/*
      - qsmxt/scripts/*
      - qsmxt/workflows/*
    
jobs:
  setup_qsmxt:
    runs-on: ubuntu-20.04
    outputs:
      setup-complete: 'true'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Setup QSMxT
      env:
        TEST_DIR: "/tmp"
        REQUIRED_VERSION_TYPE: "TEST_PACKAGE_VERSION"
      run: |
        /bin/bash qsmxt/tests/setup_qsmxt.sh apptainer
  test_transparent_singularity_pipeline:
    needs: setup_qsmxt
    runs-on: ubuntu-20.04
    steps:
    - name: Run transparent-singularity pipeline
      env:
        WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
        WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        FREEIMAGE_KEY: ${{ secrets.FREEIMAGE_KEY }}
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
        OSF_USER: ${{ secrets.OSF_USER }}
        OSF_PASS: ${{ secrets.OSF_PASS }}
        TEST_DIR: "/tmp"
      run: |
        TEST_CONTAINER_VERSION=$(cat ${TEST_DIR}/QSMxT/docs/_config.yml | grep 'TEST_CONTAINER_VERSION' | awk '{print $2}')
        TEST_CONTAINER_DATE=$(cat ${TEST_DIR}/QSMxT/docs/_config.yml | grep 'TEST_CONTAINER_DATE' | awk '{print $2}')
        export PATH="${TEST_DIR}/qsmxt_${TEST_CONTAINER_VERSION}_${TEST_CONTAINER_DATE}:${PATH}"
        export PROD_MINICONDA_PATH="${TEST_DIR}/miniconda3"
        source ${PROD_MINICONDA_PATH}/etc/profile.d/conda.sh
        export PATH="${PROD_MINICONDA_PATH}/bin:${PATH}"

        echo "[DEBUG] echo ${TEST_DIR}/qsmxt_${TEST_CONTAINER_VERSION}_${TEST_CONTAINER_DATE}:${PATH}"
        echo "${TEST_DIR}/qsmxt_${TEST_CONTAINER_VERSION}_${TEST_CONTAINER_DATE}:${PATH}"

        echo "[DEBUG] echo ${PATH}"
        echo "${PATH}"

        echo "[DEBUG] which dcm2niix"
        which dcm2niix
    
        echo "[DEBUG] which conda && which python && which pip && which qsmxt && which julia"
        which conda && which python && which pip && which qsmxt && which julia
    
        echo "[DEBUG] conda activate qsmxt"
        conda activate qsmxt

        ./qsmxt/tests/test_transparent_singularity.sh

