name: transparent apptainer test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - setup.py
      - .github/workflows/test_transparent_apptainer.yml
      - docs/_includes/miniforge_install.sh
      - docs/_includes/transparent_apptainer_install.sh
      - aseg_labels.csv
      - qsmxt/qsm_pipelines.json
      - qsmxt/cli/*.py
      - qsmxt/tests/test_transparent_apptainer.sh
      - qsmxt/tests/utils.py
      - qsmxt/tests/setup_qsmxt.sh
      - qsmxt/interfaces/*
      - qsmxt/scripts/*
      - qsmxt/workflows/*

jobs:
  test_transparent_apptainer_pipeline:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Setup QSMxT
      env:
        # Use runner-specific directory to avoid conflicts with parallel runs
        TEST_DIR: "/storage/tmp/${{ runner.name }}"
        REQUIRED_VERSION_TYPE: "TEST_PACKAGE_VERSION"
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
        OSF_USERNAME: ${{ secrets.OSF_USER }}
        OSF_PASSWORD: ${{ secrets.OSF_PASS }}
      run: |
        ./qsmxt/tests/setup_qsmxt.sh apptainer
    - name: test transparent apptainer
      env:
        WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
        WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        FREEIMAGE_KEY: ${{ secrets.FREEIMAGE_KEY }}
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
        OSF_USERNAME: ${{ secrets.OSF_USER }}
        OSF_PASSWORD: ${{ secrets.OSF_PASS }}
        RUN_ID: ${{ github.run_id }}
        # Use runner-specific directory to avoid conflicts with parallel runs
        TEST_DIR: "/storage/tmp/${{ runner.name }}"
      run: |
        TEST_CONTAINER_VERSION=$(cat ${TEST_DIR}/QSMxT/docs/_config.yml | grep 'TEST_CONTAINER_VERSION' | awk '{print $2}')
        TEST_CONTAINER_DATE=$(cat ${TEST_DIR}/QSMxT/docs/_config.yml | grep 'TEST_CONTAINER_DATE' | awk '{print $2}')
        export PATH="${TEST_DIR}/qsmxt_${TEST_CONTAINER_VERSION}_${TEST_CONTAINER_DATE}:${PATH}"
        export PROD_MINIFORGE_PATH="${TEST_DIR}/miniforge3"
        source ${PROD_MINIFORGE_PATH}/etc/profile.d/conda.sh
        export PATH="${PROD_MINIFORGE_PATH}/bin:${PATH}"

        echo "[DEBUG] echo ${TEST_DIR}/qsmxt_${TEST_CONTAINER_VERSION}_${TEST_CONTAINER_DATE}:${PATH}"
        echo "${TEST_DIR}/qsmxt_${TEST_CONTAINER_VERSION}_${TEST_CONTAINER_DATE}:${PATH}"

        echo "[DEBUG] echo ${PATH}"
        echo "${PATH}"

        echo "[DEBUG] which dcm2niix"
        which dcm2niix

        echo "[DEBUG] which conda && which python && which pip && which qsmxt && which julia"
        which conda && which julia

        echo "[DEBUG] conda activate qsmxt"
        conda activate qsmxt

        echo "[DEBUG] which python && which pip && which qsmxt && which dicom-convert && which nifti-convert"
        which python && which pip && which qsmxt && which dicom-convert && which nifti-convert

        ./qsmxt/tests/test_transparent_apptainer.sh

