name: test QSM,segmentation and template pipelines

on:
  push:
    branches: [ master ]
    paths-ignore:
      - diagram.png
      - aseg_labels.csv
      - run_1_fixGEphaseFFTshift.py
      - README.md
      - .gitignore
  pull_request:
    branches: [ master ]
    paths-ignore:
      - .gitignore
      - diagram.png
      - aseg_labels.csv
      - run_1_fixGEphaseFFTshift.py
      - README.md
    
env:
  container: vnmd/qsmxt_1.1.4:20210611

jobs:
  # test_qsm_pipeline:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Free up space
  #     uses: easimon/maximize-build-space@master
  #     with:
  #       root-reserve-mb: 40000
  #       swap-size-mb: 1024
  #       remove-dotnet: 'true'
  #       remove-android: 'true'
  #       remove-haskell: 'true'
  #       overprovision-lvm: 'true'
  #   - name: Move docker installation
  #     run: |
  #         sudo mv /var/lib/docker /home/runner/work/docker
  #         sudo ln -s /home/runner/work/docker /var/lib/docker
  #         sudo systemctl restart docker
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: test QSM pipeline
  #     run: |
  #       /bin/bash tests/run_test_qsm.sh
  # test_template_pipeline:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Free up space
  #     uses: easimon/maximize-build-space@master
  #     with:
  #       root-reserve-mb: 40000
  #       swap-size-mb: 1024
  #       remove-dotnet: 'true'
  #       remove-android: 'true'
  #       remove-haskell: 'true'
  #       overprovision-lvm: 'true'
  #   - name: Move docker installation
  #     run: |
  #         sudo mv /var/lib/docker /home/runner/work/docker
  #         sudo ln -s /home/runner/work/docker /var/lib/docker
  #         sudo systemctl restart docker
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #   - name: test template pipeline
  #     run: |
  #       /bin/bash tests/run_test_template.sh
  test_segmentation_pipeline:
    runs-on: self-hosted
    steps:
    - name: test segmentation pipeline
      run: |
        [ -d  /tmp/QSMxT ] && rm -rf /tmp/QSMxT     
        git clone https://github.com/QSMxT/QSMxT.git /tmp/QSMxT
        /bin/bash /tmp/QSMxT/tests/run_test_segment.sh