name: transparent singularity test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/test_transparent_singularity.yml
      - README.md
      - dicom_sort.py
      - dicom_convert.py
      - nifti_convert.py
      - qsmxt.py
      - tests/test_transparent_singularity.sh
      - tests/utils.py
      - interfaces/*
      - scripts/*
      - workflows/*
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/test_transparent_singularity.yml
      - README.md
      - dicom_sort.py
      - dicom_convert.py
      - nifti_convert.py
      - qsmxt.py
      - tests/test_transparent_singularity.sh
      - tests/utils.py
      - interfaces/*
      - scripts/*
      - workflows/*
    
jobs:
  test_transparent_singularity_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: test transparent singularity
      run: |
        /bin/bash tests/test_transparent_singularity.sh

