name: segmentation pipeline test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ master ]
    paths:
      - README.md
      - run_0_dicomSort.py
      - run_1_dicomConvert.py
      - run_3_segment.py
      - run_5_analysis.py
      - interfaces/nipype_interface_fastsurfer.py
      - .github/workflows/test_segmentation_pipeline.yml
      - tests/test_segment.sh
      - aseg_labels.csv
  pull_request:
    branches: [ master ]
    paths:
      - README.md
      - run_0_dicomSort.py
      - run_1_dicomConvert.py
      - run_3_segment.py
      - run_5_analysis.py
      - interfaces/nipype_interface_fastsurfer.py
      - .github/workflows/test_segmentation_pipeline.yml
      - tests/test_segment.sh
      - aseg_labels.csv
    
jobs:
  test_segmentation_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Free up space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 30000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - name: Move docker installation
      run: |
          sudo mv /var/lib/docker /home/runner/work/docker
          sudo ln -s /home/runner/work/docker /var/lib/docker
          sudo systemctl restart docker
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: segmentation pipeline
      run: |
        /bin/bash tests/test_segment.sh
