name: qsm pipeline test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ master ]
    paths:
      - README.md
      - run_0_dicomSort.py
      - run_1_dicomConvert.py
      - run_2_qsm.py
      - interfaces/nipype_interface_addtojson.py
      - interfaces/nipype_interface_axialsampling.py
      - interfaces/nipype_interface_bet2.py
      - interfaces/nipype_interface_erode.py
      - interfaces/nipype_interface_json.py
      - interfaces/nipype_interface_laplacian_unwrapping.py
      - interfaces/nipype_interface_makehomogeneous.py
      - interfaces/nipype_interface_masking.py
      - interfaces/nipype_interface_nextqsm.py
      - interfaces/nipype_interface_nonzeroaverage.py
      - interfaces/nipype_interface_phaseweights.py
      - interfaces/nipype_interface_romeo.py
      - interfaces/nipype_interface_scalephase.py
      - interfaces/nipype_interface_tgv_qsm.py
      - interfaces/nipype_interface_twopass.py
      - scripts/makehomogeneous.jl
      - scripts/qsmjl_full.jl
      - scripts/qsmjl_laplacian_unwrapping.jl
      - scripts/qsmjl_pdf.jl
      - scripts/qsmjl_rts.jl
      - scripts/qsmjl_tv.jl
      - scripts/qsmjl.vsharp.jl
      - scripts/romeo_unwrapping.jl
      - scripts/romeo_voxelquality.jl
      - scripts/logger.py
      - scripts/qsmxt_functions.py
      - .github/workflows/test_qsm_pipeline.yml
      - tests/run_test_qsm.sh
      - tests/run_test_qsm.py
  pull_request:
    branches: [ master ]
    paths:
      - README.md
      - run_0_dicomSort.py
      - run_1_dicomConvert.py
      - run_2_qsm.py
      - interfaces/nipype_interface_addtojson.py
      - interfaces/nipype_interface_axialsampling.py
      - interfaces/nipype_interface_bet2.py
      - interfaces/nipype_interface_erode.py
      - interfaces/nipype_interface_json.py
      - interfaces/nipype_interface_laplacian_unwrapping.py
      - interfaces/nipype_interface_makehomogeneous.py
      - interfaces/nipype_interface_masking.py
      - interfaces/nipype_interface_nextqsm.py
      - interfaces/nipype_interface_nonzeroaverage.py
      - interfaces/nipype_interface_phaseweights.py
      - interfaces/nipype_interface_romeo.py
      - interfaces/nipype_interface_scalephase.py
      - interfaces/nipype_interface_tgv_qsm.py
      - interfaces/nipype_interface_twopass.py
      - scripts/makehomogeneous.jl
      - scripts/qsmjl_full.jl
      - scripts/qsmjl_laplacian_unwrapping.jl
      - scripts/qsmjl_pdf.jl
      - scripts/qsmjl_rts.jl
      - scripts/qsmjl_tv.jl
      - scripts/qsmjl.vsharp.jl
      - scripts/romeo_unwrapping.jl
      - scripts/romeo_voxelquality.jl
      - scripts/logger.py
      - scripts/qsmxt_functions.py
      - .github/workflows/test_qsm_pipeline.yml
      - tests/run_test_qsm.sh
      - tests/run_test_qsm.py
    
jobs:
  test_qsm_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Free up space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 40000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - name: Move docker installation
      run: |
          sudo mv /var/lib/docker /home/runner/work/docker
          sudo ln -s /home/runner/work/docker /var/lib/docker
          sudo systemctl restart docker
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Test QSM pipeline
      env:
        DOWNLOAD_URL: ${{ secrets.DOWNLOAD_URL }}
        UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
        DATA_PASS: ${{ secrets.DATA_PASS }}
      run: |
        /bin/bash tests/run_test_qsm.sh
    - uses: actions/upload-artifact@v3
      with:
        name: public-outputs
        path: /tmp/public-outputs

