name: template pipeline test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - diagram.png
      - aseg_labels.csv
      - run_1_fixGEphaseFFTshift.py
      - run_3_segment.py
      - run_0_dicomSort.py
      - run_1_dicomToBids.py
      - run_2_qsm.py
      - README.md
      - .gitignore
      - .github/workflows/test_qsm_pipeline.yml
      - .github/workflows/test_segmentation_pipeline.yml
      - tests/run_test_segment.sh
      - tests/run_test_qsm.sh
  pull_request:
    branches: [ master ]
    paths-ignore:
      - .gitignore
      - diagram.png
      - aseg_labels.csv
      - run_1_fixGEphaseFFTshift.py
      - run_3_segment.py
      - run_0_dicomSort.py
      - run_1_dicomToBids.py
      - run_2_qsm.py
      - README.md
      - .github/workflows/test_qsm_pipeline.yml
      - .github/workflows/test_segmentation_pipeline.yml
      - tests/run_test_segment.sh
      - tests/run_test_qsm.sh
    
jobs:
  test_template_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Free up space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 40000
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - name: Move docker installation
      run: |
          sudo mv /var/lib/docker /home/runner/work/docker
          sudo ln -s /home/runner/work/docker /var/lib/docker
          sudo systemctl restart docker
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: test template pipeline
      run: |
        /bin/bash tests/run_test_template.sh