name: transparent singularity test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ '**' ]
    paths:
      - setup.py
      - .github/workflows/test_transparent_singularity.yml
      - docs/_includes/miniconda_install.sh
      - docs/_includes/transparent_singularity_install.sh
      - docs/_config.yml
      - aseg_labels.csv
      - qsmxt/qsm_pipelines.json
      - qsmxt/cli/*.py
      - qsmxt/tests/test_transparent_singularity.sh
      - qsmxt/tests/utils.py
      - qsmxt/tests/setup_qsmxt.sh
      - qsmxt/interfaces/*
      - qsmxt/scripts/*
      - qsmxt/workflows/*
    
jobs:
  test_transparent_singularity_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Setup QSMxT
      env:
        TEST_DIR: "/tmp"
        REQUIRED_VERSION_TYPE: "TEST_PACKAGE_VERSION"
      run: |
        /bin/bash qsmxt/tests/setup_qsmxt.sh apptainer
    - name: test transparent singularity
      env:
        WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
        WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        FREEIMAGE_KEY: ${{ secrets.FREEIMAGE_KEY }}
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
        OSF_USER: ${{ secrets.OSF_USER }}
        OSF_PASS: ${{ secrets.OSF_PASS }}
        TEST_DIR: "/tmp"
      run: |
        export PATH="${TEST_DIR}/qsmxt_${TEST_CONTAINER_VERSION}_${TEST_CONTAINER_DATE}:${PATH}"
        export PROD_MINICONDA_PATH="${TEST_DIR}/miniconda3"
        source ${PROD_MINICONDA_PATH}/etc/profile.d/conda.sh
        export PATH=${PROD_MINICONDA_PATH}/bin:${PATH}
    
        echo "[DEBUG] which conda && which python && which pip"
        which conda && which python && which pip
    
        echo "[DEBUG] conda activate qsmxt"
        conda activate qsmxt

        /bin/bash qsmxt/tests/test_transparent_singularity.sh

