name: template pipeline test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/test_template.yml
      - README.md
      - qsmxt.py
      - tests/test_template.sh
      - tests/test_template.py
      - tests/utils.py
      - scripts/logger.py
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/test_template.yml
      - README.md
      - qsmxt.py
      - tests/test_template.sh
      - tests/test_template.py
      - tests/utils.py
      - scripts/logger.py
    
jobs:
  test_template:
    runs-on: "cirun-oracle--${{ github.run_id }}"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Setup QSMxT
      run: |
        /bin/bash tests/setup_qsmxt.sh
    - name: Run template pipeline
      env:
        WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
        WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        FREEIMAGE_KEY: ${{ secrets.FREEIMAGE_KEY }}
        OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
      run: |
        /bin/bash tests/test_template.sh "test_template"
    - uses: actions/upload-artifact@v3
      with:
        name: public-outputs
        path: /tmp/public-outputs

