name: transparent singularity test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: [ '**' ]
    paths:
      - setup.py
      - .github/workflows/test_transparent_singularity.yml
      - docs/_includes/miniconda_install.sh
      - docs/_includes/transparent_singularity_install.sh
      - docs/_config.yml
      - aseg_labels.csv
      - qsmxt/qsm_pipelines.json
      - qsmxt/cli/dicom_sort.py
      - qsmxt/cli/dicom_convert.py
      - qsmxt/cli/nifti_convert.py
      - qsmxt/cli/main.py
      - qsmxt/tests/test_transparent_singularity.sh
      - qsmxt/tests/utils.py
      - qsmxt/interfaces/*
      - qsmxt/scripts/*
      - qsmxt/workflows/*
    
jobs:
  test_transparent_singularity_pipeline:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Extract software_version and build_date from docs/_config.yml
      id: vars
      run: |
        SOFTWARE_VERSION=$(yq eval '.SOFTWARE_VERSION' docs/_config.yml)
        BUILD_DATE=$(yq eval '.BUILD_DATE' docs/_config.yml)
        echo "SOFTWARE_VERSION=$SOFTWARE_VERSION" >> $GITHUB_ENV
        echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
    - name: test transparent singularity
      run: |
        sed "s/#SOFTWARE_VERSION#/$SOFTWARE_VERSION/g; s/#BUILD_DATE#/$BUILD_DATE/g" qsmxt/tests/test_transparent_singularity.sh > qsmxt/tests/test_transparent_singularity.sh
        /bin/bash qsmxt/tests/test_transparent_singularity.sh

